import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig } from '@playwright/test';

const E2E_PASSPHRASE = 'e2e-passphrase';
const E2E_API_KEY = 'test-key-do-not-leak';
const E2E_UPSTREAM_BASE_URL = 'http://127.0.0.1:4100';

// FEAT-003 T-031: materialize Angular env files at config-eval time, before
// Playwright spawns ng serve as a webServer entry. Doing this in globalSetup
// is too late — ng serve has already compiled with whatever values were on
// disk and tests run before HMR finishes re-bundling.
const ENV_CONTENT = `// Auto-generated by playwright.config.ts. Do not edit.
import type { EnvironmentConfig } from './environment.example';
export const environment: EnvironmentConfig = {
  production: false,
  orchestratorBaseUrl: '${E2E_UPSTREAM_BASE_URL}',
  orchestratorApiKey: '${E2E_API_KEY}',
  operatorPassphrase: '${E2E_PASSPHRASE}',
};
`;
writeFileSync(resolve(__dirname, 'src/environments/environment.ts'), ENV_CONTENT);
writeFileSync(resolve(__dirname, 'src/environments/environment.prod.ts'), ENV_CONTENT);

export default defineConfig({
  testDir: './e2e',
  fullyParallel: false,
  forbidOnly: !!process.env['CI'],
  retries: process.env['CI'] ? 2 : 0,
  workers: 1,
  reporter: [['list'], ['html', { open: 'never' }]],
  globalSetup: './e2e/global-setup.ts',
  use: {
    baseURL: 'http://localhost:4200',
    trace: 'on-first-retry',
  },
  webServer: [
    // BFF webServer entry was retired with FEAT-003 T-032. The SPA hits the
    // orchestrator (here, the in-process e2e mock on 127.0.0.1:4100) directly.
    {
      command: 'npm run start',
      port: 4200,
      reuseExistingServer: !process.env['CI'],
      timeout: 120_000,
    },
  ],
});

export { E2E_PASSPHRASE, E2E_API_KEY };
